swagger: "2.0"
consumes:
  - application/json
produces:
  - application/json
host: localhost:8010
info:
  $ref: ./info.yaml
paths:
  $ref: ./paths.yaml
definitions:
  $ref: ./definitions.yaml
