swagger: '2.0'
consumes:
  - application/json
produces:
  - application/json
host: 'localhost:8010'
info:
  title: Nailed Opinion Mining API Server
  description: >-
    This is a sample server NailedOM server. For this sample, you can use the
    api key `special-key` to test the authorization filters.
  version: '0.1'
paths:
  /api/user:
    get:
      summary: Gets the current user
      description: ''
      tags:
        - User
      operationId: getuser
      consumes:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad request
        '401':
          description: Unauthorized access
        '500':
          description: Unexpected error (internal error)
  /api/user/signin:
    post:
      summary: Logs user into the system
      description: ''
      tags:
        - User
      operationId: signinuser
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: The user object for login
          required: true
          schema:
            $ref: '#/definitions/SignIn'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/SignInResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized access
        '500':
          description: Unexpected error (internal error)
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
  SignIn:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  SignInResponse:
    type: object
    properties:
      token:
        type: string
